export enum AppRoutes {
  SIGN_IN = "SIGN IN",
  SIGN_UP = "SIGN UP",
  REQUEST_PASSWORD_RESET = "REQUEST PASSWORD RESET",
  RESET_PASSWORD = "RESET PASSWORD",
  VERIFY_PHONE_NUMBER = "Verification",
}
