export enum AppRoutes {
  LOGIN = "SIGN IN",
  REGISTER = "REGISTER",
  REQUEST_PASSWORD_RESET = "REQUEST PASSWORD RESET",
  RESET_PASSWORD = "RESET PASSWORD",
  VERIFY_PHONE_NUMBER = "PHONE NUMBER VERIFY",
}
